from dataclasses import dataclass, field

from boatrace.common import ColumnsMixin
from boatrace.common import ColumnDatatype
from boatrace.common.cast_function import Datetime, Name, Age, Weight


@dataclass
class RaceCardColumns(ColumnsMixin):
    race_id:            ColumnDatatype = field(default_factory=lambda: ColumnDatatype("レースID", int))
    stadium_id:         ColumnDatatype = field(default_factory=lambda: ColumnDatatype("レース場ID", int))
    date:               ColumnDatatype = field(default_factory=lambda: ColumnDatatype("開催日程", Datetime))
    frame:              ColumnDatatype = field(default_factory=lambda: ColumnDatatype("枠", int))
    racer_id:           ColumnDatatype = field(default_factory=lambda: ColumnDatatype("レーサ-登録番号", int))
    racer_class:        ColumnDatatype = field(default_factory=lambda: ColumnDatatype("レーサ-級別", str))
    racer_name:         ColumnDatatype = field(default_factory=lambda: ColumnDatatype("レーサ-氏名", Name))
    racer_branch:       ColumnDatatype = field(default_factory=lambda: ColumnDatatype("レーサ-支部", str))
    racer_birthplace:   ColumnDatatype = field(default_factory=lambda: ColumnDatatype("レーサ-出身地", str))
    racer_age:          ColumnDatatype = field(default_factory=lambda: ColumnDatatype("レーサ-年齢", Age))
    racer_weight:       ColumnDatatype = field(default_factory=lambda: ColumnDatatype("レーサ-体重", Weight))
    racer_fn:           ColumnDatatype = field(default_factory=lambda: ColumnDatatype("レーサ-F数", str))
    racer_ln:           ColumnDatatype = field(default_factory=lambda: ColumnDatatype("レーサ-L数", str))
    racer_avgst:        ColumnDatatype = field(default_factory=lambda: ColumnDatatype("レーサ-平均ST", float))
    national_1rate:     ColumnDatatype = field(default_factory=lambda: ColumnDatatype("全国-勝率", float))
    national_2rate:     ColumnDatatype = field(default_factory=lambda: ColumnDatatype("全国-2連率", float))
    national_3rate:     ColumnDatatype = field(default_factory=lambda: ColumnDatatype("全国-3連率", float))
    locale_1rate:       ColumnDatatype = field(default_factory=lambda: ColumnDatatype("当地-勝率", float))
    locale_2rate:       ColumnDatatype = field(default_factory=lambda: ColumnDatatype("当地-2連率", float))
    locale_3rate:       ColumnDatatype = field(default_factory=lambda: ColumnDatatype("当地-3連率", float))
    motor_no:           ColumnDatatype = field(default_factory=lambda: ColumnDatatype("モータ-No", int))
    motor_2rate:        ColumnDatatype = field(default_factory=lambda: ColumnDatatype("モータ-2連率", float))
    motor_3rate:        ColumnDatatype = field(default_factory=lambda: ColumnDatatype("モータ-3連率", float))
    boat_no:            ColumnDatatype = field(default_factory=lambda: ColumnDatatype("ボート-No", int))
    boat_2rate:         ColumnDatatype = field(default_factory=lambda: ColumnDatatype("ボート-2連率", float))
    boat_3rate:         ColumnDatatype = field(default_factory=lambda: ColumnDatatype("ボート-3連率", float))
    day1_race_no:       ColumnDatatype = field(default_factory=lambda: ColumnDatatype("1日目-レースNo", int))
    day1_entry_no:      ColumnDatatype = field(default_factory=lambda: ColumnDatatype("1日目-進入コース", int))
    day1_st_timing:     ColumnDatatype = field(default_factory=lambda: ColumnDatatype("1日目-STタイミング", float))
    day1_rank:          ColumnDatatype = field(default_factory=lambda: ColumnDatatype("1日目-成績", int))
    day2_race_no:       ColumnDatatype = field(default_factory=lambda: ColumnDatatype("2日目-レースNo", int))
    day2_entry_no:      ColumnDatatype = field(default_factory=lambda: ColumnDatatype("2日目-進入コース", int))
    day2_st_timing:     ColumnDatatype = field(default_factory=lambda: ColumnDatatype("2日目-STタイミング", float))
    day2_rank:          ColumnDatatype = field(default_factory=lambda: ColumnDatatype("2日目-成績", int))
    day3_race_no:       ColumnDatatype = field(default_factory=lambda: ColumnDatatype("3日目-レースNo", int))
    day3_entry_no:      ColumnDatatype = field(default_factory=lambda: ColumnDatatype("3日目-進入コース", int))
    day3_st_timing:     ColumnDatatype = field(default_factory=lambda: ColumnDatatype("3日目-STタイミング", float))
    day3_rank:          ColumnDatatype = field(default_factory=lambda: ColumnDatatype("3日目-成績", int))
    day4_race_no:       ColumnDatatype = field(default_factory=lambda: ColumnDatatype("4日目-レースNo", int))
    day4_entry_no:      ColumnDatatype = field(default_factory=lambda: ColumnDatatype("4日目-進入コース", int))
    day4_st_timing:     ColumnDatatype = field(default_factory=lambda: ColumnDatatype("4日目-STタイミング", float))
    day4_rank:          ColumnDatatype = field(default_factory=lambda: ColumnDatatype("4日目-成績", int))
    day5_race_no:       ColumnDatatype = field(default_factory=lambda: ColumnDatatype("5日目-レースNo", int))
    day5_entry_no:      ColumnDatatype = field(default_factory=lambda: ColumnDatatype("5日目-進入コース", int))
    day5_st_timing:     ColumnDatatype = field(default_factory=lambda: ColumnDatatype("5日目-STタイミング", float))
    day5_rank:          ColumnDatatype = field(default_factory=lambda: ColumnDatatype("5日目-成績", int))
    day6_race_no:       ColumnDatatype = field(default_factory=lambda: ColumnDatatype("6日目-レースNo", int))
    day6_entry_no:      ColumnDatatype = field(default_factory=lambda: ColumnDatatype("6日目-進入コース", int))
    day6_st_timing:     ColumnDatatype = field(default_factory=lambda: ColumnDatatype("6日目-STタイミング", float))
    day6_rank:          ColumnDatatype = field(default_factory=lambda: ColumnDatatype("6日目-成績", int))
    day7_race_no:       ColumnDatatype = field(default_factory=lambda: ColumnDatatype("7日目-レースNo", int))
    day7_entry_no:      ColumnDatatype = field(default_factory=lambda: ColumnDatatype("7日目-進入コース", int))
    day7_st_timing:     ColumnDatatype = field(default_factory=lambda: ColumnDatatype("7日目-STタイミング", float))
    day7_rank:          ColumnDatatype = field(default_factory=lambda: ColumnDatatype("7日目-成績", int))
